"""Centralized production constants for CityTwin AI."""

# Data quality pipeline
IQR_MULTIPLIER = 1.5
QUALITY_WEIGHT_MISSING = 3.0
QUALITY_WEIGHT_DUPLICATES = 2.0
QUALITY_WEIGHT_OUTLIERS = 1.5
MAX_PENALTY_MISSING = 30.0
MAX_PENALTY_DUPLICATES = 20.0
MAX_PENALTY_OUTLIERS = 20.0

# Risk assessment engine
RISK_THRESHOLD_MEDIUM = 0.40
RISK_THRESHOLD_HIGH = 0.65
RISK_THRESHOLD_CRITICAL = 0.85

# Congestion parameters
DEFAULT_ROAD_CAPACITY = 7500.0
TRAFFIC_NORMALIZATION_FACTOR = 100.0

# Pollution parameters
AQI_THRESHOLD_MEDIUM = 150.0
AQI_THRESHOLD_HIGH = 200.0
AQI_THRESHOLD_CRITICAL = 300.0

# Digital twin simulation
SIM_MODAL_SHIFT_FACTOR = 0.15
SIM_MAX_MODAL_SHIFT = 0.45
SIM_ADD_ROAD_TRAFFIC_REDUCTION = 0.90
SIM_BUILD_HOSPITAL_COVERAGE_INCREASE = 22.0
SIM_BUILD_HOSPITAL_TRAFFIC_INCREASE = 1.04
SIM_GRAVITY_ROAD_BASE_TRAVEL_TIME = 20.0

# Parameter bounds
BOUNDS_ADD_BUSES = (1, 500)
BOUNDS_POPULATION_GROWTH = (1, 100)
BOUNDS_RESTRICT_VEHICLES = (1, 100)
BOUNDS_HORIZON_DAYS = (1, 90)

# API and system
RATE_LIMIT_PER_MINUTE = 10
RATE_LIMIT_WINDOW_SECONDS = 60
MAX_UPLOAD_BYTES = 50 * 1024 * 1024
ANALYTICS_CACHE_TTL_SECONDS = 1800
MODEL_ARTIFACT_DIR = "ml/artifacts"
